Front End Pull Request
H-isaac23/CodeWars pull request #4
Opened 2023-11-22 12:28 UTC by JayAlvinCVallescas

Add new feature in front end

2023-11-27 13:23 UTC, H-isaac23 requested changes
Delete lang package-lock.json

2023-11-27 13:23 UTC, H-isaac23 commented on package-lock.json
delete to hahaha

2023-11-30 13:28 UTC, H-isaac23 requested changes
delete package-lock.json aaaaaaaaaaaaaaaaaaaaaaaaaaa

2023-11-30 13:28 UTC, H-isaac23 commented on package-lock.json
hoiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii andito pa rin hahaha

2023-11-30 13:39 UTC, H-isaac23 approved these changes
lgtm

2023-11-30 13:39 UTC, merged

2023-11-30 13:49 UTC, JayAlvinCVallescas commented
Okkiii